keycloak:
  url:
  username: {}
  password: {}
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi
operatorImage: keycloak-realm-operator # (This default gets replaced by Tilt or CI)
