keycloak:
  url:
  username:
    value: nil
    # valueFrom:
    #   secretKeyRef:
    #     name:
    #     key:
  password:
    value: nil
    # valueFrom:
    #   secretKeyRef:
    #     name:
    #     key:
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi
