apiVersion: k8s.rightcrowd.com/v1alpha1
kind: KeycloakClientScope
metadata:
  name: funny-client-scope
spec:
  realm: funny
  id: test-scope
  prune: true
  claim: true
  representation:
    description: OpenID Connect scope for add user roles to the access token
    protocol: openid-connect
    # type: default