apiVersion: k8s.rightcrowd.com/v1alpha1
kind: KeycloakClientCredential
metadata:
  name: supersecret-keycloak-client-sync
spec:
  realm: rightcrowd-core
  clientId: that-one-client
  targetSecretName: supersecret-keycloak-client-secret
