apiVersion: k8s.rightcrowd.com/v1alpha1
kind: KeycloakClientCredential
metadata:
  name: employee-app-tenman-secret-sync
spec:
  realm: rightcrowd-core
  clientId: employee-app-tenant-manager
  targetSecretName: employee-app-tenant-manager-secret
