apiVersion: k8s.rightcrowd.com/v1alpha1
kind: KeycloakClientCredential
metadata:
  name: supersecret-keycloak-client-sync
spec:
  realm: funny
  clientId: funny-client
  targetSecretName: supersecret-keycloak-client-secret
  ## ⬇️ Optional
  fallbackStrategy: skip # Default is "skip". Can be set to "error" to fail the reconciliation if the client is not found in Keycloak.
  targetSecretTemplate:
    - key: realm
      template: {{ .realm }}
    - key: clientId
      template: {{ .clientId }}
    - key: clientSecret
      template: {{ .clientSecret }}
    - key: connectionString
      template: "https://{{ .clientId }}:{{ .clientSecret }}@funny-shop-api"