apiVersion: k8s.rightcrowd.com/v1alpha1
kind: KeycloakClientCredential
metadata:
  name: some-client-credential
  namespace: default
spec:
  realm: funny
  clientId: funny-client
  targetSecretName: some-client-credential-secret
