apiVersion: k8s.rightcrowd.com/v1alpha1
kind: KeycloakClientCredential
metadata:
  name: some-client-credential
  namespace: default
spec:
  realm: master
  clientId: admin-cli
  targetSecretName: some-client-credential-secret
