apiVersion: k8s.rightcrowd.com/v1alpha1
kind: KeycloakClient
metadata:
  name: funny-client
spec:
  realm: funny
  clientId: funny-client
  name: Funny Client
  prune: true
  claim: true
  scopes:
    default:
      - test-scope
  representation:
    implicitFlowEnabled: true