apiVersion: v1
kind: Secret
metadata:
  name: client-with-defined-secret-secret
  namespace: default
type: Opaque
data:
  secret: Y3VzdG9tIHNlY3JldCBnb2VzIGhlcmU=
---
apiVersion: k8s.rightcrowd.com/v1alpha1
kind: KeycloakClient
metadata:
  name: client-with-defined-secret
spec:
  realm: funny
  clientId: client-with-defined-secret
  name: Client With Defined Secret
  prune: true
  claim: true
  secret:
    valueFrom:
      secretKeyRef:
        name: client-with-defined-secret-secret
        namespace: default
        key: secret
  representation:
    implicitFlowEnabled: true
