apiVersion: k8s.rightcrowd.com/v1alpha1
kind: ManagedKeycloakRealm
metadata:
  name: funny-realm
spec:
  realmId: funny
  displayName: Funny Haha
  pruneRealm: true
  claimRealm: true
  representation:
    loginWithEmailAllowed: false
    registrationEmailAsUsername: true
    emailTheme: keycloak
    displayNameHtml: "<h5>Funny Realm</h5>"