apiVersion: k8s.rightcrowd.com/v1alpha1
kind: ManagedKeycloakRealm
metadata:
  name: funny-realm
spec:
  realmId: funny
  displayName: Funny Haha
  pruneRealm: true
  clients:
    - id: funnt-client
      name: Super Funny Client
      type: oidc
      clientAuthenticationEnabled: true
      secretTargets:
        - namespace: weird-namespace
          name: synced-kc-client-secret

