apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managedkeycloakrealms.k8s.rightcrowd.com
spec:
  group: k8s.rightcrowd.com
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                realmId:
                  type: string
                displayName:
                  type: string
                pruneRealm:
                  type: boolean
              required:
                - realmId
            status:
              type: object
              properties:
                lastOperatorStatusUpdate:
                  type: string
      additionalPrinterColumns:
        - name: RealmName
          type: string
          description: The name of the realm
          jsonPath: .spec.realmName
  # either Namespaced or Cluster
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  names:
    plural: managedkeycloakrealms
    singular: managedkeycloakrealm
    kind: ManagedKeycloakRealm
    shortNames:
    - mkcr
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []