apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: managed-keycloak-realm-operator
      automountServiceAccountToken: true
      containers:
      - name: operator
        image: operator
        env:
          - name: KEYCLOAK_URL
            value: {{ .Values.keycloak.url }}
          - name: KEYCLOAK_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: username
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secrets
                key: password
          - name: REDIS_CONNECTION_STRING
            value: redis://operator-redis-svc:6379
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
