apiVersion: v1
kind: ServiceAccount
metadata:
  name: managed-keycloak-realm-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: managedkeycloakrealm
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloak-realm-controller
rules:
- apiGroups: ["k8s.rightcrowd.com"]
  resources: ["managedkeycloakrealms"]
  verbs: ["*"]
- apiGroups: ["k8s.rightcrowd.com"]
  resources: ["managedkeycloakrealms/status"]
  verbs: ["*"]
- apiGroups: ["k8s.rightcrowd.com"]
  resources: ["keycloakclientcredentials"]
  verbs: ["*"]
- apiGroups: ["k8s.rightcrowd.com"]
  resources: ["keycloakclientcredentials/status"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: managed-keycloak-realm-operator-cluster-role-binding
roleRef:
  kind: ClusterRole
  name: keycloak-realm-controller
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: managed-keycloak-realm-operator
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: managedkeycloakrealm
  namespace: default