build:operator:
  needs: []
  stage: build
  # only:
  #   variables:
  #     - $CI_COMMIT_TAG =~ /^\d+.\d+.\d+-?.*$/
  extends:
    - .buildImageTemplate
  variables:
    DOCKERFILE_LOCATION: 'dockerfile'
    IMAGE_NAME: 'keycloak-realm-operator'
    VERSION: $CI_COMMIT_TAG

build:operator-helm-chart:
  stage: build-manifests
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^\d+.\d+.\d+-?.*$/
  image: alpine
  before_script:
    - apk add yq helm
  script:
    - yq -i '.operatorImage = "rightcrowd.azurecr.io/keycloak-realm-operator:\(env(CI_COMMIT_TAG))"' ./k8s/helm/values.yaml
    - yq -i '.version = env(CI_COMMIT_TAG)' ./k8s/helm/Chart.yaml
    - helm package ./k8s/helm
    - helm push "keycloak-realm-operator-chart-$CI_COMMIT_TAG.tgz" oci://rightcrowd.azurecr.io/keycloak-realm-operator-chart